### ISSUE TITLE
controller menu

### ISSUE THREAD

**Issue by arjundubey-cr** [arjundubey-cr/hand-it-out#2]
**controller menu**
a menu through which font-size, font-face, etc will be handled.

**Comment by osmankbk** [comment]
Hi! Can I please work on this?

**Comment by arjundubey-cr** [comment]
Hi @osmankbk I've already completed the requirements for this issue, but i would really appreciate your contribution in future issues 😊

**Comment by osmankbk** [comment]
Yea, I'd like that, thank you!
